; PlatformIO Project Configuration File

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 921600

